version: "3.3"

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - UMASK=022
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${SHARE_DIRECTORY}/movies:/movies
      - ${SHARE_DIRECTORY}/downloads:/downloads
      - ${CONFIG_DIRECTORY}/radarr:/config
      - /mnt/external-hard-drive/temporary-file-tunnel:/temporary-file-tunnel
    ports:
      - 7878:7878/tcp
    depends_on:
      - "prowlarr"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=${TZ}
      - UMASK=022
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_DIRECTORY}/sonarr:/config
      - ${SHARE_DIRECTORY}/tv:/tv
      - ${SHARE_DIRECTORY}/downloads:/downloads
      - /mnt/external-hard-drive/temporary-file-tunnel:/temporary-file-tunnel
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - "prowlarr"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
    volumes:
      - ${CONFIG_DIRECTORY}/bazarr:/config
      - ${SHARE_DIRECTORY}/movies:/movies
      - ${SHARE_DIRECTORY}/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    depends_on:
      - "prowlarr"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - UMASK=022
    volumes:
      - /home/tom/server-config/plex:/config
      - ${SHARE_DIRECTORY}/tv:/tv
      - ${SHARE_DIRECTORY}/movies:/movies
      - ${SHARE_DIRECTORY}/music:/music
      - ${SHARE_DIRECTORY}/pictures:/pictures
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VALIDATION=duckdns
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=false
      - URL=${DUCKDNS_URL}
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      - EMAIL=${DUCKDNS_EMAIL}
    volumes:
      - ${CONFIG_DIRECTORY}/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIRECTORY}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    depends_on:
      - "qbittorrent"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIRECTORY}/readarr:/config
      - ${SHARE_DIRECTORY}/books:/books
      - ${SHARE_DIRECTORY}/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_DIRECTORY}/qbittorrent:/config
      - ${SHARE_DIRECTORY}/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
